#  ____    _            __        __                    #
# / ___|  | | __  _   _ \ \      / /  __ _  _ __  ___   #
# \___ \  | |/ / | | | | \ \ /\ / /  / _` || '__|/ __|  #
#  ___) | |   <  | |_| |  \ V  V /  | (_| || |   \__ \  #
# |____/  |_|\_\  \__, |   \_/\_/    \__,_||_|   |___/  #
#                 |___/                                 #
#                                 By ShotaDev(KubiG25)  #
#-------------------------------------------------------#
settings:
  data-player-type: SQLITE
  announce-update: true
  per-tab-world: true
#-------------------------------------------------------#
dependencies:
  placeholder-api: false
  slime-world-manager: false
  parties: false
#-------------------------------------------------------#
connection:
  hostname: localhost
  port: 3306
  database: database
  username: username
  password: password
#-------------------------------------------------------#
lobby-options:
  spawn: none
  stat-hologram: none
  teleport-on-join: true
  protection-guard: true
#-------------------------------------------------------#