#  ____    _            __        __                    #
# / ___|  | | __  _   _ \ \      / /  __ _  _ __  ___   #
# \___ \  | |/ / | | | | \ \ /\ / /  / _` || '__|/ __|  #
#  ___) | |   <  | |_| |  \ V  V /  | (_| || |   \__ \  #
# |____/  |_|\_\  \__, |   \_/\_/    \__,_||_|   |___/  #
#                 |___/                                 #
#                                 By ShotaDev(KubiG25)  #
#-------------------------------------------------------#
options:
  data-type: SQLITE
  announce-update: true
  teleport-on-join: false
  placeholderapi: false
  slime-world-manager: false
  parties: false
  pertabworld: true
#-------------------------------------------------------#
connection:
  hostname: localhost
  port: 3306
  database: database
  username: username
  password: password
#-------------------------------------------------------#
lobbySpawn: none
holoSpawn: none
#-------------------------------------------------------#
lobby-protect:
  enabled: true
  options:
    hunger: true
    damage: true
    interact: true
    build: true
    destroy: true
#-------------------------------------------------------#