#-----------------------------------------------------------------------#
player-settings:
  save-inventory: true
  titles: true
  actionbar: true
  sounds: true
  default-cosmetics:
    cages: 0
    kits-normal: 0
    kits-ranked: 0
    trails: 999
    death-cries: 999
    kill-effects: 999
    balloons: 999
    victory-dances: 999
#-----------------------------------------------------------------------#
game-options:
  waiting-lobby: true
  votes-default:
    chest: NORMAL
    health: NORMAL
    time: DAY
    weather: SUNNY
  ranked-mode:
    level-required: 0
    wins-required: 50
    kills-required: 50
  distance-between-cages: 4
  command-whitelist:
    enabled: true
    list:
      - leave
  countdowns:
    starting: 11
    pregame: 6
    ending: 6
  events-priority-and-time:
    - refill;180
    - refill;120
    - ender_dragon;120
#-----------------------------------------------------------------------#
sounds:
  join: none
  quit: none
  starting: block_note_block_pling
  pregame: entity_arrow_hit_player
  playing: entity_firework_rocket_launch
  ending: none
#-----------------------------------------------------------------------#
points:
  money:
    per-kill:
      min: 1
      max: 5
    per-win:
      min: 1
      max: 5
  experience:
    per-kill:
      min: 1
      max: 5
    per-win:
      min: 1
      max: 5
#-----------------------------------------------------------------------#